language: cpp
compiler: gcc
os: linux

branches:
  only:
    - /.*/

notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

env:
  global:
    - CFLAGS="-Wall -Wextra -pedantic -Wconversion "
    - CXXFLAGS="-Wall -Wextra -pedantic -Wconversion"
before_install:
  - pip install --user cpp-coveralls
  - eval "${MATRIX_EVAL}"
  - which $CC
  - which $CXX
  - $CC --version
  - $CXX --version
install:
  - mkdir Build
  - cd Build
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov

before_script:
  - lcov --directory . --zerocounters

script:
  - cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Coverage
  - make
  - ctest -V

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'googletest/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info